clc;
clear;

global C sk init f4 ts;
global den hZ vZ theta mw CAw mys CAys D0 densy densystar Lsh cord densh scalesk ts;
C = 0.775; %阻力系数
sk = 0;
init = figure('Numbertitle','off',...
                     'Name','降落伞开伞过程计算软件');
set(init, 'Visible', 'off'); % 先设置窗口为隐藏，再创建对象，最后设为可见
set(init, 'Position', [0 0 800 600]);
movegui(init, 'center');
set(init, 'MenuBar', 'figure'); % 显示标准菜单栏
set(init, 'ToolBar', 'figure'); % 显示标准工具栏

TextWidth = 110;
TextHeight = 22;
EditWidth = 100;
EditHeight = 30;
ButtonWidth = 100;
ButtonHeight = 20;
LTextPos = 80;
LEditPos = 220;
RTextPos = 455;
REditPos = 615;

%% 框架f1 开伞工况
f1 = uicontrol('Style', 'frame',...
                       'Position', [10 395 385 190]);
f1n = uicontrol('Style', 'text',...
                         'Position', [20 575 80 20],...
                         'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                         'String', '开伞工况');
f1t1 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f1n.Position(2)-10-EditHeight/2-TextHeight/2 TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '空气密度',...
                          'HorizontalAlignment', 'left');
f1t2 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f1t1.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '高度',...
                          'HorizontalAlignment', 'left');
f1t3 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f1t2.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '速度',...
                          'HorizontalAlignment', 'left');
f1t4 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f1t3.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '倾斜角',...
                          'HorizontalAlignment', 'left');
f1e1 = uicontrol('Style', 'edit',...
                           'Position', [LEditPos f1n.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f1e2 = uicontrol('Style', 'edit',...
                           'Position', [LEditPos f1e1.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f1e3 = uicontrol('Style', 'edit',...
                           'Position', [LEditPos f1e2.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f1e4 = uicontrol('Style', 'edit',...
                           'Position', [LEditPos f1e3.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);

%% 框架f2 载荷
f2 = uicontrol('Style', 'frame',...
                       'Position', [10 f1.Position(2)-10*5-EditHeight*2-f1n.Position(4) 385 10*5+EditHeight*2]);
f2n = uicontrol('Style', 'text',...
                         'Position', [20 f2.Position(2)+f2.Position(4)-10 45 20],...
                         'FontSize', 13,...
                         'FontName', 'Microsoft YaHei UI',...
                         'String', '载荷');
f2t1 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f2n.Position(2)-10-EditHeight/2-TextHeight/2 TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '质量',...
                          'HorizontalAlignment', 'left');
f2t2 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f2t1.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '阻力特征',...
                          'HorizontalAlignment', 'left');
f2e1 = uicontrol('Style', 'edit',...
                          'Position', [LEditPos f2n.Position(2)-10-EditHeight EditWidth EditHeight],...
                          'FontSize', 12);
f2e2 = uicontrol('Style', 'edit',...
                           'Position', [LEditPos f2e1.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);

%% 框架f3 引导伞
f3 = uicontrol('Style', 'frame',...
                       'Position', [10 f2.Position(2)-10*5-EditHeight*2-f1n.Position(4) 385 10*5+EditHeight*2]);
f3n = uicontrol('Style', 'text',...
                         'Position', [20 f3.Position(2)+f3.Position(4)-10 60 20],...
                         'FontSize', 13,...
                         'FontName', 'Microsoft YaHei UI',...
                         'String', '引导伞');
f3t1 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f3n.Position(2)-10-EditHeight/2-TextHeight/2 TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '质量',...
                          'HorizontalAlignment', 'left');
f3t2 = uicontrol('Style', 'text',...
                          'Position', [LTextPos f3t1.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '阻力特征',...
                          'HorizontalAlignment', 'left');
f3e1 = uicontrol('Style', 'edit',...
                          'Position', [LEditPos f3n.Position(2)-10-EditHeight EditWidth EditHeight],...
                          'FontSize', 12);
f3e2 = uicontrol('Style', 'edit',...
                           'Position', [LEditPos f3e1.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);

%% 框架f4 主伞
f4 = uicontrol('Style', 'frame',...
                       'Position', [405 135 385 450]);

f4n = uicontrol('Style', 'text',...
                           'Position', [415 575 45 20],...
                           'FontSize', 13,...
                           'FontName', 'Microsoft YaHei UI',...
                           'String', '主伞');
f4t1 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4n.Position(2)-10*2-EditHeight/2-TextHeight/2 TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '伞型',...
                          'HorizontalAlignment', 'left');

%按钮组bg1
bg1 = uibuttongroup('Units', 'pixels',...
                                   'Position',[REditPos f4n.Position(2)-10*5-ButtonHeight*3 ButtonWidth+20 ButtonHeight*3+10*4]);

f4b1 = uicontrol(bg1,'Style', 'radiobutton',...
                           'FontSize', 12,...
                           'FontName', '黑体',...
                           'String', '平面圆伞',...
                           'Position',[10 10*3+ButtonHeight*2 ButtonWidth ButtonHeight],... %以bg为父对象，原点在bg左下角
                           'Callback', 'C = 0.775');
f4b2 = uicontrol(bg1,'Style','radiobutton',...
                           'FontSize', 12,...
                           'FontName', '黑体',...
                           'String','环帆伞',...
                           'Position',[10 10*2+ButtonHeight*1 ButtonWidth ButtonHeight],...
                           'Callback', 'C = 0.8');
f4b3 = uicontrol(bg1,'Style','radiobutton',...
                           'FontSize', 12,...
                           'FontName', '黑体',...
                           'String','锥形伞',...
                           'Position',[10 10 ButtonWidth ButtonHeight],...
                           'Callback', 'C = 0.9');                   

f4t2 = uicontrol('Style', 'text',...
                          'Position', [RTextPos bg1.Position(2)-10-EditHeight/2-TextHeight/2 TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '名义直径',...
                          'HorizontalAlignment', 'left');
f4t3 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4t2.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '伞衣密度',...
                          'HorizontalAlignment', 'left');
f4t4 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4t3.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '伞衣底边密度',...
                          'HorizontalAlignment', 'left');
f4t5 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4t4.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '伞绳长度',...
                          'HorizontalAlignment', 'left');
f4t6 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4t5.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '伞绳个数',...
                          'HorizontalAlignment', 'left');
f4t7 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4t6.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '伞绳密度',...
                          'HorizontalAlignment', 'left');

f4e2 = uicontrol('Style', 'edit',...
                           'Position', [REditPos bg1.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f4e3 = uicontrol('Style', 'edit',...
                           'Position', [REditPos f4e2.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f4e4 = uicontrol('Style', 'edit',...
                           'Position', [REditPos f4e3.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f4e5 = uicontrol('Style', 'edit',...
                           'Position', [REditPos f4e4.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f4e6 = uicontrol('Style', 'edit',...
                           'Position', [REditPos f4e5.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);
f4e7 = uicontrol('Style', 'edit',...
                           'Position', [REditPos f4e6.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'FontSize', 12);

f4t8 = uicontrol('Style', 'text',...
                          'Position', [RTextPos f4e7.Position(2)-10-EditHeight TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '收口情况',...
                          'HorizontalAlignment', 'left');

%按钮组bg1
bg2 = uibuttongroup('Units', 'pixels',...
                                   'Position',[REditPos f4e7.Position(2)-10*4-ButtonHeight*2 ButtonWidth+20 ButtonHeight*2+10*3]);

f4b4 = uicontrol(bg2,'Style', 'radiobutton',...
                           'FontSize', 12,...
                           'FontName', '黑体',...
                           'String', '无收口',...
                           'Position',[10 10*2+ButtonHeight ButtonWidth ButtonHeight],... %以bg为父对象，原点在bg左下角
                           'Callback', ['set(f4, ''Position'', [405 135 385 450]);'...
                                             'set([f4t9 f4t10 f4e9 f4e10], {''Visible''}, {''off''});'...
                                             'set(f5p1, ''Position'',[340 50 120 50]);'...
                                             'sk = 0']);
f4b5 = uicontrol(bg2,'Style','radiobutton',...
                           'FontSize', 12,...
                            'FontName', '黑体',...
                           'String','一次收口',...
                           'Position',[10 10 ButtonWidth ButtonHeight],...
                           'Callback', ['set(f4, ''Position'', [405 20 385 565]);'...
                                             'set([f4t9 f4t10 f4e9 f4e10], {''Visible''}, {''on''});'...
                                             'set(f5p1, ''Position'',[140 50 120 50]);'...
                                             'sk = 1']);
                       
f4t9 = uicontrol('Style', 'text',...
                          'Position', [RTextPos bg2.Position(2)-10-EditHeight/2-TextHeight/2 TextWidth TextHeight],...
                          'FontSize', 13,...
                          'FontName', 'Microsoft YaHei UI',...
                          'String', '收口比',...
                          'Visible', 'off',...
                          'HorizontalAlignment', 'left');
f4t10 = uicontrol('Style', 'text',...
                           'Position', [RTextPos f4t9.Position(2)-10-EditHeight TextWidth TextHeight],...
                           'FontSize', 13,...
                           'FontName', 'Microsoft YaHei UI',...
                           'String', '收口时间',...
                           'Visible', 'off',...
                           'HorizontalAlignment', 'left');
f4e9 = uicontrol('Style', 'edit',...
                           'Position', [REditPos bg2.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'Visible', 'off',...
                           'FontSize', 12);
f4e10 = uicontrol('Style', 'edit',...
                           'Position', [REditPos f4e9.Position(2)-10-EditHeight EditWidth EditHeight],...
                           'Visible', 'off',...
                           'FontSize', 12);

%% 计算按钮
f5p1 = uicontrol('Style', 'pushbutton',...
                           'Position', [340 50 120 50],...
                           'FontSize', 16,...
                            'FontName', '黑体',...
                           'String', '开始计算',...
                           'Callback', ['den = str2num(get(f1e1, ''String''));'...
                                              'hZ = str2num(get(f1e2, ''String''));'...
                                              'vZ = str2num(get(f1e3, ''String''));'...
                                              'theta = str2num(get(f1e4, ''String''));'...
                                              'mw = str2num(get(f2e1, ''String''));'...
                                              'CAw = str2num(get(f2e2, ''String''));'...
                                              'mys = str2num(get(f3e1, ''String''));'...
                                              'CAys = str2num(get(f3e2, ''String''));'...
                                              'D0 = str2num(get(f4e2, ''String''));'...
                                              'densy = str2num(get(f4e3, ''String''));'...
                                              'densystar = str2num(get(f4e4, ''String''));'...
                                              'Lsh = str2num(get(f4e5, ''String''));'...
                                              'cord = str2num(get(f4e6, ''String''));'...
                                              'densh = str2num(get(f4e7, ''String''));'...
                                              'scalesk = str2num(get(f4e9, ''String''));'...
                                              'ts = str2num(get(f4e10, ''String''));'...
                                              'run(''main.m'');'...
                                              'run(''gui2.m'')']);                           

%%
set(init,'CloseRequestFcn', ['button = questdlg(''你确定退出吗？'', ''退出'', ''是'', ''否'', ''是'');'...
                                           'if strcmp(button, ''是'')',...
                                                 'delete(init);'...
                                           'end']);
set(init, 'Visible', 'on');