global t2 v Fk f4 init gr dtrailx dtraily itrailx itraily FL me;
fig = figure('Numbertitle','off',...
                    'Name','图像生成',...
                    'MenuBar', 'none',...
                    'Position', [0 0 700 570],...
                    'deletefcn', 'figure(init)');
set(fig, 'Visible', 'off');

movegui(fig, 'center');

back =  uicontrol('Style', 'pushbutton',...
                            'FontSize', 14,...
                            'FontName', '黑体',...
                            'String', '返回',...
                            'Position', [20 100 100 50],...
                            'Callback', ['close(fig);'...
                                              'figure(init)']);                                       
save =  uicontrol('Style', 'pushbutton',...
                            'FontSize', 14,...
                            'String', '保存图像',...
                            'FontName', '黑体',...
                            'Position', [20 260 100 50],...
                            'Callback', ['[FileName,FilePath] = uiputfile({''*.jpg'',''JPEG(*.jpg)''}, ''保存图像'', title);'...
                                                'set(gca, ''Units'', ''pixels'');'...
                                                'pos = get(gca, ''Position'');'...
                                                'ti = get(gca, ''TightInset'');'...
                                                'rect = [-ti(1),-ti(2),pos(3)+ti(1)+2*ti(3),pos(4)+ti(2)+ti(4)];'...
                                                'F = getframe(gca, rect);'...
                                                'if ~isequal([FileName,FilePath], [0,0]),',...
                                                    'FileFullName = [FilePath,FileName];'...
                                                    'imwrite(F.cdata, FileFullName);'...
                                                'end']);
                                            
gr = 0; % 网格标识符
ctrlgrid = uicontrol('Style', 'pushbutton',...
                                  'FontSize', 14,...
                                  'FontName', '黑体',...
                                  'String', '显示网格',...
                                  'Position', [20 420 100 50],...
                                  'Callback', ['if gr == 0,',... % 注意if、else的后面要加逗号
                                                        'grid on;'...
                                                        'gr = 1;'...
                                                        'set(ctrlgrid, ''String'', ''隐藏网格'');'...
                                                    'else,',...
                                                        'grid off;'...
                                                        'gr = 0;'...
                                                        'set(ctrlgrid, ''String'', ''显示网格'');'...
                                                    'end']);

%% 背景设置
background = axes('Visible', 'off',...
                                'Units', 'normalized',...
                                'Position', [0 0 1 1]);
paint = axes('Visible', 'on',...
                    'Units', 'pixels',...
                    'Position', [195 60 480 480]);
mp = plot(paint, 0, 0);

%% 菜单栏
m1 = uimenu('Label', '拉直过程');
uimenu(m1, 'Label', '载荷部分速度Vw',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax - 1, 1), v1(1 : tmax - 1, 3));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''载荷部分速度Vw/(m/s)'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程载荷部分速度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '引导伞部分速度Vys',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax, 1), v1(1 : tmax, 4));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''引导伞部分速度Vys/(m/s)'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程引导伞部分速度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '已拉出部分质量me',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax - 1, 1), v1(1 : tmax - 1, 1));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''已拉出部分质量me/kg'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程已拉出部分质量'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '已拉出长度L',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax - 1, 1), v1(1 : tmax - 1, 2));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''已拉出长度L/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程已拉出长度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '倾斜角θ',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax - 1, 1), v1(1 : tmax - 1, 5));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''倾斜角θ/°'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程倾斜角'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '水平方向位移x',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax - 1, 1), v1(1 : tmax - 1, 6));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''水平方向位移x/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程水平方向位移'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '高度h',...
                    'Callback', ['mp = plot(paint, t1(1 : tmax - 1, 1), v1(1 : tmax - 1, 7));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''高度h/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程高度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '拉直力FL',...
                    'Callback', ['mp = plot(0.01 : 0.01 : 0.01 * (tmax - 1), FL(:, 1));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''拉直力FL/N'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程拉直力'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m1, 'Label', '轨迹',...
                    'Callback', ['mp = plot(dtrailx'', dtraily'', ''-b'');'...
                                       'hold on;',...
                                       'mp1 = scatter(dtrailx(:, 1), dtraily(:, 1), ''or'');'...
                                       'mp2 = scatter(dtrailx(:, 2), dtraily(:, 2), ''sk'');'...
                                       'hold off;'...
                                       'legend([mp(1), mp1(1), mp2(1)], ''主伞已拉出部分'', ''引导伞'', ''载荷'');'... 
                                       'xlabel(''水平方向位移x/m'');'...
                                       'ylabel(''高度h/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''拉直过程轨迹'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);

m2 = uimenu('Label', '充气过程');
uimenu(m2, 'Label', '伞阻力特征CA',...
                    'Callback', ['mp = plot(paint, t2, v2(:, 1));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''伞阻力特征CA/m^2'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程伞阻力特征'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '附加质量mf',...
                    'Callback', ['mp = plot(paint, t2, v2(:, 2));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''附加质量mf/kg'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程附加质量'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '速度v',...
                    'Callback', ['mp = plot(paint, t2, v2(:, 3));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''速度v/(m/s)'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程速度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '倾斜角θ',...
                    'Callback', ['mp = plot(paint, t2, v2(:, 5));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''倾斜角θ/°'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程倾斜角'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '水平方向位移x',...
                    'Callback', ['mp = plot(paint, t2, v2(:, 6));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''水平方向位移x/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程水平方向位移'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '高度h',...
                    'Callback', ['mp = plot(paint, t2, v2(:, 7));'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''高度h/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程高度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '开伞动载Fk',...
                    'Callback', ['mp = plot(paint, t2(1 : length(t2), :), Fk);'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''开伞动载Fk/N'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程开伞动载'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m2, 'Label', '轨迹',...
                    'Callback', ['mp = plot(itrailx'', itraily'', ''-b'');'...
                                       'hold on;',...
                                       'mp1 = scatter(itrailx(:, 1), itraily(:, 1), ''or'');'...
                                       'mp2 = scatter(itrailx(:, 2), itraily(:, 2), ''sk'');'...
                                       'hold off;'...
                                       'legend([mp(1), mp1(1), mp2(1)], ''主伞伞绳'', ''主伞'', ''载荷'');'... 
                                       'xlabel(''水平方向位移x/m'');'...
                                       'ylabel(''高度h/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''充气过程轨迹'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);

m3 = uimenu('Label', '全过程');
uimenu(m3, 'Label', '系统速度v',...
                    'Callback', ['mp = plot(paint, [t1(1 : tmax - 1, 1); t2(2 : t2n) + (tmax -1) * 0.01], [v1(1 : tmax - 1, 3); v2(2 : v2n, 3)]);'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''系统速度v/(m/s)'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''全过程系统速度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m3, 'Label', '系统水平位移x',...
                    'Callback', ['mp = plot(paint, [t1(1 : tmax - 1, 1); t2(2 : t2n) + (tmax -1) * 0.01], [v1(1 : tmax - 1, 6); v2(2 : v2n, 6)]);'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''系统水平位移x/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''全过程系统水平位移'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m3, 'Label', '系统高度h',...
                    'Callback', ['mp = plot(paint, [t1(1 : tmax - 1, 1); t2(2 : t2n) + (tmax -1) * 0.01], [v1(1 : tmax - 1, 7); v2(2 : v2n, 7)]);'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''系统高度h/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''全过程系统高度'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m3, 'Label', '系统倾斜角θ',...
                    'Callback', ['mp = plot(paint, [t1(1 : tmax - 1, 1); t2(2 : t2n) + (tmax -1) * 0.01], [v1(1 : tmax - 1, 5); v2(2 : v2n, 5)]);'...
                                       'xlabel(''时间/s'');'...
                                       'ylabel(''系统倾斜角θ/°'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''全过程系统倾斜角'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);
uimenu(m3, 'Label', '全过程轨迹',...
                    'Callback', ['mp = plot([dtrailx; itrailx]'', [dtraily; itraily]'', ''-b'');'...
                                       'hold on;',...
                                       'mp1 = scatter([dtrailx(:, 1); itrailx(:, 1)], [dtraily(:, 1); itraily(:, 1)], ''or'');'...
                                       'mp2 = scatter([dtrailx(:, 2); itrailx(:, 2)], [dtraily(:, 2); itraily(:, 2)], ''sk'');'...
                                       'hold off;'...
                                       'legend([mp(1), mp1(1), mp2(1)], ''主伞已拉出部分/主伞伞绳'', ''引导伞/主伞'', ''载荷'');'... 
                                       'xlabel(''水平方向位移x/m'');'...
                                       'ylabel(''高度h/m'');'...
                                       'set(gca, ''FontSize'', 12);'...
                                       'title = ''全过程轨迹'';'...
                                       'if gr == 1,',...
                                       'grid on;'...
                                       'end']);

%% 
set(fig,'deletefcn', 'figure(init)');
set(fig, 'Visible', 'on');